# Generated by Django 3.1 on 2020-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_adminlist_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techleader',
            name='email',
            field=models.EmailField(default='to1@example.com', max_length=254),
        ),
    ]
