# Generated by Django 3.1 on 2020-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20200924_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='cidentnum',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinery',
            name='identnum',
            field=models.CharField(max_length=10),
        ),
    ]
