# Generated by Django 3.1 on 2020-10-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20201011_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='machines.company'),
            preserve_default=False,
        ),
    ]
