# Generated by Django 3.1 on 2020-10-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='machinery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='machines.machinery'),
        ),
    ]
