# Generated by Django 3.1 on 2020-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20201013_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlist',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
