# Generated by Django 3.1 on 2020-10-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runing',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
