# Generated by Django 3.1 on 2020-10-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_auto_20201016_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlist',
            name='user',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
