# Generated by Django 3.1 on 2020-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_auto_20201018_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
