# Generated by Django 3.1 on 2020-10-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0019_auto_20201019_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fueling',
            new_name='Fuelling',
        ),
    ]
