# Generated by Django 3.1 on 2020-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0020_auto_20201019_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='runing',
            name='sum_whour',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelling',
            name='kmeter',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelling',
            name='liter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='oilchange',
            name='kmeter',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oilchange',
            name='liter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='runing',
            name='end_kmeter',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runing',
            name='start_kmeter',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
