# Generated by Django 3.1 on 2020-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0021_auto_20201021_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runing',
            name='sum_whour',
            field=models.FloatField(null=True),
        ),
    ]
