# Generated by Django 3.1 on 2020-10-22 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0022_auto_20201021_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='runing',
            name='workday',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
