# Generated by Django 3.1 on 2020-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0023_runing_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelling',
            name='ftime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oilchange',
            name='ftime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
