# Generated by Django 3.1 on 2020-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0024_auto_20201022_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='runing',
            name='ssum_whour',
            field=models.FloatField(null=True),
        ),
    ]
