# Generated by Django 3.0.10 on 2020-10-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0026_auto_20201027_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelling',
            name='extime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oilchange',
            name='extime',
            field=models.FloatField(null=True),
        ),
    ]
