# Generated by Django 3.1 on 2020-11-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0027_auto_20201027_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilsample',
            name='illoanyag1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='illoanyag2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='illoanyag3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='koromtartalom1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='koromtartalom2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='koromtartalom3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='lobbanaspont1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='lobbanaspont2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='lobbanaspont3',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='osszulledek1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='osszulledek2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='osszulledek3',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='vasm_osszulledek1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='vasm_osszulledek2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='vasm_osszulledek3',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='vastartalom1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='vastartalom2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='vastartalom3',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='viszkozitas_valtozas1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='viszkozitas_valtozas2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='viszkozitas_valtozas3',
            field=models.SmallIntegerField(null=True),
        ),
    ]
