# Generated by Django 3.1 on 2020-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0028_auto_20201130_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilsample',
            name='viztartalom1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='viztartalom2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='viztartalom3',
            field=models.FloatField(null=True),
        ),
    ]
