# Generated by Django 3.1 on 2020-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0029_auto_20201207_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsample',
            name='kep1',
            field=models.ImageField(height_field=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='kep2',
            field=models.ImageField(height_field=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='kep3',
            field=models.ImageField(height_field=300, null=True, upload_to='images/'),
        ),
    ]
