# Generated by Django 3.1 on 2020-12-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0030_auto_20201208_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilsample',
            name='name1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='name2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oilsample',
            name='name3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
