# Generated by Django 3.1 on 2020-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0031_auto_20201208_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsample',
            name='kep1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='kep2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='kep3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
