# Generated by Django 3.1 on 2020-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0032_auto_20201208_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilsample',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='name3',
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='illoanyag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='illoanyag1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='illoanyag2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='illoanyag3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='koromtartalom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='koromtartalom1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='koromtartalom2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='koromtartalom3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='lobbanaspont',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='lobbanaspont1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='lobbanaspont2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='lobbanaspont3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='osszulledek',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='osszulledek1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='osszulledek2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='osszulledek3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vasm_osszulledek',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vasm_osszulledek1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vasm_osszulledek2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vasm_osszulledek3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vastartalom',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vastartalom1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vastartalom2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='vastartalom3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viszkozitas_valtozas',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viszkozitas_valtozas1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viszkozitas_valtozas2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viszkozitas_valtozas3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viztartalom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viztartalom1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viztartalom2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='viztartalom3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
