# Generated by Django 3.1 on 2020-12-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0033_auto_20201209_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilsample',
            name='illoanyag',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='koromtartalom',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='lobbanaspont',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='osszulledek',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='vasm_osszulledek',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='vastartalom',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='viszkozitas_valtozas',
        ),
        migrations.RemoveField(
            model_name='oilsample',
            name='viztartalom',
        ),
    ]
