# Generated by Django 3.1 on 2020-12-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0034_auto_20201210_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsample',
            name='minta_azonosito',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
