# Generated by Django 3.1 on 2020-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0035_auto_20201211_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsample',
            name='kep1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='kep2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='oilsample',
            name='kep3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
