# Generated by Django 3.1 on 2020-12-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_auto_20201211_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minta_azonosito', models.CharField(max_length=15, unique=True)),
                ('beerkezes_napja', models.DateField()),
                ('mintavetel_napja', models.DateField()),
                ('viszkozitas_valtozas1', models.SmallIntegerField(blank=True, null=True)),
                ('viszkozitas_valtozas2', models.SmallIntegerField(blank=True, null=True)),
                ('viszkozitas_valtozas3', models.SmallIntegerField(blank=True, null=True)),
                ('koromtartalom1', models.FloatField(blank=True, null=True)),
                ('koromtartalom2', models.FloatField(blank=True, null=True)),
                ('koromtartalom3', models.FloatField(blank=True, null=True)),
                ('osszulledek1', models.SmallIntegerField(blank=True, null=True)),
                ('osszulledek2', models.SmallIntegerField(blank=True, null=True)),
                ('osszulledek3', models.SmallIntegerField(blank=True, null=True)),
                ('vasm_osszulledek1', models.SmallIntegerField(blank=True, null=True)),
                ('vasm_osszulledek2', models.SmallIntegerField(blank=True, null=True)),
                ('vasm_osszulledek3', models.SmallIntegerField(blank=True, null=True)),
                ('vastartalom1', models.SmallIntegerField(blank=True, null=True)),
                ('vastartalom2', models.SmallIntegerField(blank=True, null=True)),
                ('vastartalom3', models.SmallIntegerField(blank=True, null=True)),
                ('viztartalom1', models.FloatField(blank=True, null=True)),
                ('viztartalom2', models.FloatField(blank=True, null=True)),
                ('viztartalom3', models.FloatField(blank=True, null=True)),
                ('illoanyag1', models.FloatField(blank=True, null=True)),
                ('illoanyag2', models.FloatField(blank=True, null=True)),
                ('illoanyag3', models.FloatField(blank=True, null=True)),
                ('lobbanaspont1', models.SmallIntegerField(blank=True, null=True)),
                ('lobbanaspont2', models.SmallIntegerField(blank=True, null=True)),
                ('lobbanaspont3', models.SmallIntegerField(blank=True, null=True)),
                ('kep1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('kep2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('kep3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilsamples', to='machines.machinery')),
            ],
        ),
        migrations.DeleteModel(
            name='OilSample',
        ),
    ]
