# Generated by Django 3.1 on 2021-01-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_sampimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampimages',
            name='sample_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
